export const COUNTRY_CODES = [
  { code: "+213", country: "Algeria" },
  { code: "+244", country: "Angola" },
  { code: "+54", country: "Argentina" },
  { code: "+61", country: "Australia" },
  { code: "+229", country: "Benin" },
  { code: "+267", country: "Botswana" },
  { code: "+55", country: "Brazil" },
  { code: "+226", country: "Burkina Faso" },
  { code: "+257", country: "Burundi" },
  { code: "+237", country: "Cameroon" },
  { code: "+1", country: "Canada" },
  { code: "+238", country: "Cape Verde" },
  { code: "+235", country: "Chad" },
  { code: "+56", country: "Chile" },
  { code: "+57", country: "Colombia" },
  { code: "+269", country: "Comoros" },
  { code: "+253", country: "Djibouti" },
  { code: "+20", country: "Egypt" },
  { code: "+240", country: "Equatorial Guinea" },
  { code: "+291", country: "Eritrea" },
  { code: "+268", country: "Eswatini" },
  { code: "+251", country: "Ethiopia" },
  { code: "+33", country: "France" },
  { code: "+241", country: "Gabon" },
  { code: "+220", country: "Gambia" },
  { code: "+49", country: "Germany" },
  { code: "+233", country: "Ghana" },
  { code: "+224", country: "Guinea" },
  { code: "+245", country: "Guinea-Bissau" },
  { code: "+91", country: "India" },
  { code: "+62", country: "Indonesia" },
  { code: "+972", country: "Israel" },
  { code: "+39", country: "Italy" },
  { code: "+225", country: "Ivory Coast" },
  { code: "+81", country: "Japan" },
  { code: "+254", country: "Kenya" },
  { code: "+266", country: "Lesotho" },
  { code: "+231", country: "Liberia" },
  { code: "+218", country: "Libya" },
  { code: "+261", country: "Madagascar" },
  { code: "+265", country: "Malawi" },
  { code: "+223", country: "Mali" },
  { code: "+222", country: "Mauritania" },
  { code: "+230", country: "Mauritius" },
  { code: "+52", country: "Mexico" },
  { code: "+212", country: "Morocco" },
  { code: "+258", country: "Mozambique" },
  { code: "+264", country: "Namibia" },
  { code: "+31", country: "Netherlands" },
  { code: "+227", country: "Niger" },
  { code: "+234", country: "Nigeria" },
  { code: "+63", country: "Philippines" },
  { code: "+250", country: "Rwanda" },
  { code: "+966", country: "Saudi Arabia" },
  { code: "+221", country: "Senegal" },
  { code: "+232", country: "Sierra Leone" },
  { code: "+65", country: "Singapore" },
  { code: "+386", country: "Slovenia" },
  { code: "+252", country: "Somalia" },
  { code: "+27", country: "South Africa" },
  { code: "+82", country: "South Korea" },
  { code: "+34", country: "Spain" },
  { code: "+46", country: "Sweden" },
  { code: "+255", country: "Tanzania" },
  { code: "+66", country: "Thailand" },
  { code: "+228", country: "Togo" },
  { code: "+216", country: "Tunisia" },
  { code: "+256", country: "Uganda" },
  { code: "+971", country: "United Arab Emirates" },
  { code: "+44", country: "United Kingdom" },
  { code: "+1", country: "United States" },
  { code: "+598", country: "Uruguay" },
  { code: "+84", country: "Vietnam" },
  { code: "+260", country: "Zambia" },
];

export const CURRENCIES = [
  // North America
  { code: "USD", name: "US Dollar" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "MXN", name: "Mexican Peso" },
  { code: "JMD", name: "Jamaican Dollar" },
  { code: "BBD", name: "Barbadian Dollar" },
  { code: "TTD", name: "Trinidad and Tobago Dollar" },
  { code: "BSD", name: "Bahamian Dollar" },
  { code: "DOP", name: "Dominican Peso" },
  { code: "HTG", name: "Haitian Gourde" },
  { code: "PAB", name: "Panamanian Balboa" },
  { code: "CRC", name: "Costa Rican Colón" },
  { code: "SVC", name: "Salvadoran Colón" },
  { code: "NIO", name: "Nicaraguan Córdoba" },
  { code: "HNL", name: "Honduran Lempira" },
  { code: "GTQ", name: "Guatemalan Quetzal" },
  { code: "BZD", name: "Belize Dollar" },

  // South America
  { code: "BRL", name: "Brazilian Real" },
  { code: "ARS", name: "Argentine Peso" },
  { code: "CLP", name: "Chilean Peso" },
  { code: "COP", name: "Colombian Peso" },
  { code: "PEN", name: "Peruvian Sol" },
  { code: "UYU", name: "Uruguayan Peso" },
  { code: "PYG", name: "Paraguayan Guaraní" },
  // { code: "VES", name: "Venezuelan Bolívar Soberano" }, // Removed
  { code: "GYD", name: "Guyanese Dollar" },
  { code: "SRD", name: "Surinamese Dollar" },

  // Europe
  { code: "EUR", name: "Euro" },
  { code: "GBP", name: "British Pound" },
  { code: "CHF", name: "Swiss Franc" },
  { code: "SEK", name: "Swedish Krona" },
  { code: "NOK", name: "Norwegian Krone" },
  { code: "DKK", name: "Danish Krone" },
  { code: "ISK", name: "Icelandic Króna" },
  { code: "PLN", name: "Polish Złoty" },
  { code: "CZK", name: "Czech Koruna" },
  { code: "HUF", name: "Hungarian Forint" },
  { code: "RON", name: "Romanian Leu" },
  { code: "BGN", name: "Bulgarian Lev" },
  { code: "HRK", name: "Croatian Kuna" },
  { code: "ALL", name: "Albanian Lek" },
  { code: "MKD", name: "Macedonian Denar" },
  { code: "BAM", name: "Bosnia and Herzegovina Convertible Mark" },
  { code: "RSD", name: "Serbian Dinar" },
  { code: "MDL", name: "Moldovan Leu" },
  // { code: "UAH", name: "Ukrainian Hryvnia" }, // Removed

  // Africa
  { code: "NGN", name: "Nigerian Naira" },
  { code: "ZAR", name: "South African Rand" },
  { code: "GHS", name: "Ghanaian Cedi" },
  { code: "KES", name: "Kenyan Shilling" },
  { code: "UGX", name: "Ugandan Shilling" },
  { code: "TZS", name: "Tanzanian Shilling" },
  { code: "RWF", name: "Rwandan Franc" },
  { code: "ETB", name: "Ethiopian Birr" },
  { code: "EGP", name: "Egyptian Pound" },
  { code: "MAD", name: "Moroccan Dirham" },
  { code: "TND", name: "Tunisian Dinar" },
  { code: "XOF", name: "West African CFA Franc" },
  { code: "XAF", name: "Central African CFA Franc" }, // Note: Used by multiple countries including some not removed.
  { code: "MUR", name: "Mauritian Rupee" },
  { code: "NAD", name: "Namibian Dollar" },
  { code: "BWP", name: "Botswanan Pula" },
  { code: "ZMW", name: "Zambian Kwacha" },
  { code: "MWK", name: "Malawian Kwacha" },
  { code: "MZN", name: "Mozambican Metical" },
  { code: "SZL", name: "Swazi Lilangeni" },
  { code: "LSL", name: "Lesotho Loti" },
  { code: "GMD", name: "Gambian Dalasi" },
  { code: "SLL", name: "Sierra Leonean Leone" },
  { code: "LRD", name: "Liberian Dollar" },
  { code: "GNF", name: "Guinean Franc" },
  // { code: "CDF", name: "Congolese Franc" }, // Removed
  // { code: "SDG", name: "Sudanese Pound" }, // Removed
  // { code: "SSP", name: "South Sudanese Pound" }, // Removed
  { code: "DJF", name: "Djiboutian Franc" },
  { code: "SOS", name: "Somali Shilling" },

  // Asia
  { code: "JPY", name: "Japanese Yen" },
  { code: "HKD", name: "Hong Kong Dollar" },
  { code: "SGD", name: "Singapore Dollar" },
  { code: "TWD", name: "New Taiwan Dollar" },
  { code: "KRW", name: "South Korean Won" },
  { code: "INR", name: "Indian Rupee" },
  { code: "IDR", name: "Indonesian Rupiah" },
  { code: "MYR", name: "Malaysian Ringgit" },
  { code: "THB", name: "Thai Baht" },
  { code: "PHP", name: "Philippine Peso" },
  { code: "VND", name: "Vietnamese Đồng" },
  { code: "KHR", name: "Cambodian Riel" },
  { code: "LAK", name: "Lao Kip" },
  // { code: "MMK", name: "Myanmar Kyat" }, // Removed
  { code: "BDT", name: "Bangladeshi Taka" },
  { code: "NPR", name: "Nepalese Rupee" },
  { code: "LKR", name: "Sri Lankan Rupee" },
  { code: "MVR", name: "Maldivian Rufiyaa" },
  { code: "BTN", name: "Bhutanese Ngultrum" },
  { code: "BND", name: "Brunei Dollar" },
  { code: "MNT", name: "Mongolian Tögrög" },
  { code: "KZT", name: "Kazakhstani Tenge" },
  { code: "KGS", name: "Kyrgyzstani Som" },
  { code: "UZS", name: "Uzbekistani Som" },
  { code: "TJS", name: "Tajikistani Somoni" },

  // Middle East
  { code: "AED", name: "United Arab Emirates Dirham" },
  { code: "SAR", name: "Saudi Riyal" },
  { code: "QAR", name: "Qatari Riyal" },
  { code: "OMR", name: "Omani Rial" },
  { code: "BHD", name: "Bahraini Dinar" },
  { code: "KWD", name: "Kuwaiti Dinar" },
  { code: "JOD", name: "Jordanian Dinar" },
  { code: "LBP", name: "Lebanese Pound" },
  // { code: "IQD", name: "Iraqi Dinar" }, // Removed
  { code: "YER", name: "Yemeni Rial" },
  { code: "ILS", name: "Israeli New Shekel" },

  // Oceania
  { code: "AUD", name: "Australian Dollar" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "FJD", name: "Fijian Dollar" },
  { code: "SBD", name: "Solomon Islands Dollar" },
  { code: "VUV", name: "Vanuatu Vatu" },
  { code: "TOP", name: "Tongan Paʻanga" },
  { code: "WST", name: "Samoan Tala" },
  { code: "XPF", name: "CFP Franc" },
  { code: "PGK", name: "Papua New Guinean Kina" },
];
