on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]

jobs:
  build-prod-external-crypto-payment:
    runs-on: ubuntu-22.04
    steps:
      - name: ︎Setup - Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: ︎Setup - AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-2

      - name: Setup Docker Image URL
        shell: bash
        env:
          REGISTRY: '586388583737.dkr.ecr.us-east-2.amazonaws.com/external-crypto-payment-ecr'
        run: |
          DOCKER_IMAGE="$REGISTRY:b${{ github.run_number }}-${{ github.sha }}"
          echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> $GITHUB_ENV
      - name: build docker image
        run: |
          docker build --progress=plain \
            -t ${{ env.DOCKER_IMAGE }} \
            -f Dockerfile .
      - name: ECR setup
        uses: aws-actions/amazon-ecr-login@v2

      - name: docker push
        run: |
          docker push ${{ env.DOCKER_IMAGE }}
      - name: Deploy via ecs-deploy script
        env:
          AWS_DEFAULT_REGION: us-east-2
          CLUSTER: prod-cluster
          SERVICE: external-crypto-payment
          IMAGE: ${{ env.DOCKER_IMAGE }}
        run: |
          curl -sSL https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy -o ecs-deploy
          chmod +x ecs-deploy
          ./ecs-deploy \
            --cluster "$CLUSTER" \
            --service-name "$SERVICE" \
            --image "$IMAGE" \
            --timeout 600