on:
  workflow_dispatch:
  push:
    branches: [ 'staging' ]

jobs:
  build-staging-external-crypto-payment:
    runs-on: ubuntu-22.04
    steps:
      - name: ︎Setup - Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: ︎Setup - AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-2

      - name: Setup Docker Image URL
        shell: bash
        env:
          REGISTRY: '511361519433.dkr.ecr.us-east-2.amazonaws.com/external-crypto-payment-ecr'
        run: |
          DOCKER_IMAGE="$REGISTRY:b${{ github.run_number }}-${{ github.sha }}"
          echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> $GITHUB_ENV
      - name: build docker image
        run: |
          docker build --progress=plain \
            -t ${{ env.DOCKER_IMAGE }} \
            -f Dockerfile .
      - name: ECR setup
        uses: aws-actions/amazon-ecr-login@v2

      - name: docker push
        run: |
          docker push ${{ env.DOCKER_IMAGE }}
      - name: deploy
        uses: silinternational/ecs-deploy@master
        with:
          aws_access_key_cmd: --aws-access-key
          aws_access_key: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID}}
          aws_secret_key_cmd: --aws-secret-key
          aws_secret_key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY}}
          cluster_cmd: --cluster
          cluster: 'stg-cluster'
          image_cmd: --image
          image: ${{ env.DOCKER_IMAGE }}
          region_cmd: --region
          region: us-east-2
          service_name_cmd: --service-name
          service_name: 'external-crypto-payment'
          timeout_cmd: --timeout
          timeout: 600